### ISSUE TITLE
Simplify the site and build process

### ISSUE THREAD

**Issue by J3RN** [CWDG/open-source-club-website#175]
## My commentary
- Much of the site is written in Jade, which is not natively supported by Jekyll. That's fine, since Jekyll is awesome and supports plugins, but the Jade plugin is really sub-par, since it requires you to copy-and-paste a ruby file into your site (`_plugins/jade.rb`) and requires `npm`. There are alternatives to Jade, such as Slim and Haml that are better supported by plugins in the form of Ruby Gems. Moving from Jade to one of these is likely to be nontrivial, but potentially could be mitigated with good regex magic.
- I'm confused as to why there's a Bundler plugin. Researched it and found nothing.
- Grunt is used to compile Coffeescript, but there's a [Jekyll plugin for it](https://github.com/jekyll/jekyll-coffeescript). :coffee: I hate Coffeescript anyways.
- Grunt is used to compile Sass, but Jekyll **natively compiles Sass**.
- Bower is used. I generally dislike Bower.
  - Bower is used to get "fontawesome" and "ubuntu-fontface" and "open-sans-fontface". Please just CDN these. Why are there three font faces at all? Let's not do that.
  - CDN jQuery
  - `normalize-scss`. Why not just use `normalize.css`?
  - The "simple search" thing is hard. Jury's out on how to replace that so Bower can be thrown out altogether.

Grunt also needs to be investigated more fully, but I've already spent over an hour on this.
## Suggested courses of action
- Create a branch. `retooling` might be a good name.
- Branch off of `retooling` to do a specific piece of the refactor, like remove Bower, per se, then, once finished, merge into `retooling`.
## To-do List
- [ ] Replace Jade with Haml or Slim, backed by a Ruby Gem.
- [ ] See if the bundler plugin actually does anything. Remove if possible.
- [ ] Remove Grunt's compilation of things that are better left to Jekyll to compile (Sass, Coffeescript)
- [ ] Replace what Bower is doing. Remove Bower.
- [ ] Investigate what Grunt is used for, replace. Remove Grunt.
- [ ] There should be no `npm` modules left. Remove node dependency. Remove `npm`.
- [ ] More?

**Comment by keeakita** [comment]
Specifically re CDNing things: There are concerns about this for privacy reasons. As a largely privacy focused org, we really don't want users to have to users automatically pull 3rd party assets and leak browser info unless it's absolutely necessary. Hosting these ourselves gets rid of the problem. If there is a way to link to these resources without having a referer sent, that would likely be good enough.

**Comment by J3RN** [comment]
Well, the natural alternative is to vendor-drop these. Which is, really, what Bower does, except Bower keeps them up-to-date (sort of). That can be your call.

**Comment by egladman** [comment]
#### fonts

The ubuntu fontface is already scheduled to be removed, see issue #84. As for the other ones, they will NOT be removed, as the remaining two fonts serve different purposes (i.e. headings & body) 

## 

#### Grunt compilation

I intentionally wrote it this way. The jekyll plugins are buggy and poorly supported. `libsass` (the JS implementation of sass) compiles faster unlike it's ruby counterpart.

## 

#### Grunt

Grunt is **extensively** used, therefore will never be removed. 

## 

#### npm

Will not be remove. I feel VERY strongly about this. I absolutely hate version controlling third-party libraries, so therefore I use bower, which requires node.

## 

#### jade

right now it isn't hurting anyone. If jade was ever removed i would insist on compiling everything to html. (foregoing haml, slim altogether)

**Comment by egladman** [comment]
@J3RN

I indeed want to use CDNs for the fonts, but @oslerw is heavily resistant. 

IMO it is asinine to self-host static content such as fonts and js libraries.

`normalize.scss` is used instead of `normalize.css` so that I can easily concat it into the remaining sass files. This way I have one less http request.

the fonts are indeed bower dependencies so that I can source the fonts locally during development.

**Comment by J3RN** [comment]
@egladman @oslerw You two fight it out about CDN vs. vendor-drop, I have no horse in this race.

If you'd like to use JavaScript tooling instead of the Jekyll/Ruby tooling, why not migrate to a JavaScript static-site framework? It'd probably be less painless at this point than trying to switch to Ruby tooling. A quick Google suggests [Wintersmith](http://wintersmith.io/) or [Metalsmith](http://metalsmith.io).

**Comment by egladman** [comment]
@J3RN @oslerw  fixed the jQuery CDN problem 4f5c422cb066871e24436965a60bb503d884ab5a

**Comment by egladman** [comment]
removed the bundler plugin as it was used in-conjunction with another plugin that is no longer used 0335d3a00a544dd6b5f4c943c29b024a9bed5750

**Comment by egladman** [comment]
@J3RN After much thought and **i will** replace all `.jade` files with `.html`. This way people will have to learn one less thing if they wish to contribute to the site.

I'm still on the fence about coffeescript.

**Comment by smacz42** [comment]
#### WILL NOT FIX - new site
